### ISSUE TITLE
Rubric Goals

### ISSUE THREAD

**Issue by andrewvallejo** [andrewvallejo/old-york-times#3]
These are the features required to achieve MVP

## Checklist

- [x] A list of articles #5 
- [x] A “detailed” view for each article (as opposed to summary/list view) #7
- [x] Articles in the list must link to the detailed article view you create #7
- [x] Some sort of search, filter, OR sort #6

## Further comments

[A link to the rubric](https://mod4.turing.edu/projects/take_home/take_home_fe)
